### ISSUE TITLE
官方的一个笔误

### ISSUE THREAD

**Issue by GoddessLuBoYan** [fmzquant/fmz_extend_api_demo#2]
app.py 第65-67行 函数plugin_run内

if pair is None:
    piar = get_default_stock(e.eid)

不应该是piar，应该是pair

**Comment by GoddessLuBoYan** [comment]
哦，应该这么改
if pair is None:
    _pair = get_default_stock(e.eid)
else:
    _pair = pair
        settings["exchanges"].append({"eid": e.eid, "pair": _pair, "meta" :{"AccessKey": e.accessKey, "SecretKey": e.secretKey}})
#上一行中的pair改成了_pair

**Comment by fmzquant** [comment]
多谢指出, 已更正~~
