### ISSUE TITLE
get_exchange_list 报错了,报错原因是 https://www.fmz.com/chart/symbols.json这个json文件不在了

### ISSUE THREAD

**Issue by danerlt** [fmzquant/fmz_extend_api_demo#5]
![image](https://user-images.githubusercontent.com/14197717/83725612-caf9b100-a674-11ea-94fb-fb8d065b5baa.png)

![image](https://user-images.githubusercontent.com/14197717/83725698-eebcf700-a674-11ea-8ed5-bfd22365a145.png)

**Comment by fmzquant** [comment]
加上了, 顺便更新了下hub模板, 这个只做为演示. 产品使用请二次开发
